# Generated by Django 5.2.8 on 2025-11-17 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateField(default=django.utils.timezone.now)),
                ('n1', models.PositiveIntegerField()),
                ('n2', models.PositiveIntegerField()),
                ('n3', models.PositiveIntegerField()),
                ('n4', models.PositiveIntegerField()),
                ('n5', models.PositiveIntegerField()),
                ('n6', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-round'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('is_auto', models.BooleanField(default=False)),
                ('numbers', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=1000)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto_app.draw')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
